name: AI PR Review Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Debug: Print PR diff
      - name: Get PR Diff
        env:
          GITHUB_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
        run: |
          echo "Fetching PR diff for PR #${{ github.event.pull_request.number }}"
          curl -s -H "Accept: application/vnd.github.v3.diff" \
               -H "Authorization: token $GITHUB_TOKEN" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > pr_diff.txt

          echo "----- 📝 PR DIFF -----"
          cat pr_diff.txt
          echo "----- END PR DIFF -----"

      # ✅ Debug: Print raw Gemini response
      - name: Generate AI Summary using Gemini
        id: ai
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Generating AI-based PR summary using Gemini..."
          RAW_RESPONSE=$(curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"contents\": [{
                \"parts\": [{\"text\": \"You are a senior Flutter developer and code reviewer. Summarize this PR based on the following diff:\n\n$(cat pr_diff.txt | sed 's/\"/\\\"/g')\"}]
              }]
            }")

          echo "----- 🤖 RAW GEMINI RESPONSE -----"
          echo "$RAW_RESPONSE"
          echo "----- END RAW RESPONSE -----"

          SUMMARY=$(echo "$RAW_RESPONSE" | jq -r '.candidates[0].content.parts[0].text')

          echo "----- ✅ AI SUMMARY -----"
          echo "$SUMMARY"
          echo "----- END SUMMARY -----"

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post AI Summary as Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🤖 Gemini AI PR Review Summary\n\n${{ steps.ai.outputs.summary }}`
            })
