jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load .env variables
        uses: xom9ikk/dotenv@v2
        with:
          path: ./.env   # 👈 ensure correct path

      - name: Print token (for debug)
        run: echo "Token is $PR_COMMENT_TOKEN"

      - name: Get PR Diff
        run: |
          echo "Fetching PR diff for PR #${{ github.event.pull_request.number }}"
          curl -s -H "Accept: application/vnd.github.v3.diff" \
               -H "Authorization: token $PR_COMMENT_TOKEN" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > pr_diff.txt
