name: AI PR Review Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Load .env variables
      - name: Load .env variables
        uses: xom9ikk/dotenv@v2
        with:
          path: ./.env

      - name: Get PR Diff
        run: |
          echo "Fetching PR diff for PR #${{ github.event.pull_request.number }}"
          curl -s -H "Accept: application/vnd.github.v3.diff" \
               -H "Authorization: token $PR_COMMENT_TOKEN" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > pr_diff.txt

      - name: Generate AI Summary
        id: ai
        run: |
          SUMMARY=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "{
              \"model\": \"gpt-4o-mini\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"You are a senior Flutter developer and code reviewer. Provide a concise PR review summary.\"},
                {\"role\": \"user\", \"content\": \"Summarize this PR based on the following diff:\n\n$(cat pr_diff.txt | sed 's/\"/\\\"/g')\"}
              ]
            }" | jq -r '.choices[0].message.content')

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post AI Summary as Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.PR_COMMENT_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🤖 AI PR Review Summary\n\n${{ steps.ai.outputs.summary }}`
            });