name: AI PR Review Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PR_COMMENT_TOKEN secret is set
        run: |
          if [ -z "${{ secrets.PR_COMMENT_TOKEN }}" ]; then
            echo "PR_COMMENT_TOKEN secret is NOT set."
            exit 1
          else
            echo "PR_COMMENT_TOKEN secret is available."
          fi

      - name: Get Full PR Diff
        id: diff
        env:
          GITHUB_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
        run: |
          echo "Fetching full PR diff for PR #${{ github.event.pull_request.number }}"
          curl -s -H "Accept: application/vnd.github.v3.diff" \
               -H "Authorization: token $GITHUB_TOKEN" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > pr_diff.txt

          if [ $? -ne 0 ]; then
            echo "Error fetching PR diff."
            exit 1
          fi

          echo "----- First 50 lines for preview -----"
          head -n 50 pr_diff.txt

      - name: Extract Jira Issue Key
        id: issue_key
        run: |
          ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Za-z]+-[0-9]+' | tr '[:lower:]' '[:upper:]')
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT

      - name: Fetch Jira Description
        id: jira
        env:
          JIRA_EMAIL: "anil.stpaul142@gmail.com"
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          echo "Fetching Jira issue description for ${{ steps.issue_key.outputs.issue_key }}"
          RESPONSE=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" \
            "https://tusharnigam88.atlassian.net/rest/api/3/issue/${{ steps.issue_key.outputs.issue_key }}")
          
          echo "----- RAW JIRA RESPONSE -----"
          echo "$RESPONSE"

          DESCRIPTION=$(echo "$RESPONSE" | jq -r '.fields.description.content[]?.content[]?.text' | tr '\n' ' ')
          echo "description<<EOF" >> $GITHUB_OUTPUT
          echo "$DESCRIPTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check PR Size
        id: pr_size
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            core.setOutput("changed_files", pullRequest.changed_files);

      - name: Generate Class-Wise AI Review
        id: ai
        if: steps.pr_size.outputs.changed_files <= 100
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Generating class-wise AI review..."

          DIFF_CONTENT=$(cat pr_diff.txt)
          JIRA_DESC="${{ steps.jira.outputs.description }}"

          PR_DIFF=$(echo "$DIFF_CONTENT" | base64 -w 0)
          DESCRIPTION=$(echo "$JIRA_DESC" | base64 -w 0)

          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"contents\": [{
                \"parts\": [{
                  \"text\": \"You are a senior Flutter reviewer. Decode the base64 PR diff and Jira description. Merge them to generate a review:\n\nBase64 PR diff:\n$PR_DIFF\n\nBase64 Jira Description:\n$DESCRIPTION\n\nFor each class, describe:\n- Purpose\n- Changes made\n- Potential issues or risks\n- Testing notes\nOutput in Markdown with headings for each file and class.\"
                }]
              }]
            }")

          echo "----- RAW GEMINI RESPONSE -----"
          echo "$RESPONSE"

          SUMMARY=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          echo "----- Extracted Summary -----"
          echo "$SUMMARY"

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post Class-Wise Review as PR Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
          script: |
            const summary = `${{ steps.ai.outputs.summary }}`;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "### 🧠 AI PR Review (Class-Wise with Jira Context)\n\n" + summary
            });
