name: AI PR Review Summary (Gemini)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout PR code
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Check if secret is available
      - name: Check if GEMINI_API_KEY is set
        run: |
          if [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then
            echo "❌ GEMINI_API_KEY secret is NOT set."
            exit 1
          else
            echo "✅ GEMINI_API_KEY is available."
          fi

      # 2️⃣ Get PR Diff
      - name: Get PR Diff
        env:
          GITHUB_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
        run: |
          echo "📂 Fetching PR diff for PR #${{ github.event.pull_request.number }}"
          curl -s -H "Accept: application/vnd.github.v3.diff" \
               -H "Authorization: token $GITHUB_TOKEN" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > pr_diff.txt

          echo "----- 📜 PR Diff Start -----"
          cat pr_diff.txt
          echo "----- 📜 PR Diff End -----"

      # 3️⃣ Generate AI Summary using Gemini
      - name: Generate AI Summary using Gemini
        id: ai
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "🤖 Generating AI-based PR summary using Gemini..."

          # ✅ Encode PR diff safely
          DIFF_CONTENT=$(base64 -w 0 pr_diff.txt)

          RAW_RESPONSE=$(curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"contents\": [{
                \"parts\": [{
                  \"text\": \"You are a senior Flutter developer and code reviewer. Summarize this PR based on the following diff (Base64 encoded). Decode it first, then write summary:\n\n$DIFF_CONTENT\"
                }]
              }]
            }")

          echo "----- 🤖 RAW GEMINI RESPONSE -----"
          echo "$RAW_RESPONSE"
          echo "----- END RAW RESPONSE -----"

          SUMMARY=$(echo "$RAW_RESPONSE" | jq -r '.candidates[0].content.parts[0].text')

          echo "----- ✅ AI SUMMARY -----"
          echo "$SUMMARY"
          echo "----- END SUMMARY -----"

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 4️⃣ Post AI Summary as PR Comment
      - name: Post AI Summary as Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🤖 AI PR Review Summary (Gemini)\n\n${{ steps.ai.outputs.summary }}`
            })
