name: AI PR Review Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PR_COMMENT_TOKEN secret is set
        run: |
          if [ -z "${{ secrets.PR_COMMENT_TOKEN }}" ]; then
            echo "PR_COMMENT_TOKEN secret is NOT set."
            exit 1
          else
            echo "PR_COMMENT_TOKEN secret is available."
          fi

      - name: Get Full PR Diff
        id: diff
        env:
          GITHUB_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
        run: |
          echo "Fetching full PR diff for PR #${{ github.event.pull_request.number }}"
          curl -s -H "Accept: application/vnd.github.v3.diff" \
               -H "Authorization: token $GITHUB_TOKEN" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > pr_diff.txt

          if [ $? -ne 0 ]; then
            echo "Error fetching PR diff."
            exit 1
          fi

          echo "----- First 50 lines for preview -----"
          head -n 50 pr_diff.txt

      - name: Fetch Jira Issue Key from PR Title
        id: jira_key
        run: |
          ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Za-z]+-[0-9]+' | tr '[:lower:]' '[:upper:]')
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT
          echo "Detected Jira Issue Key: $ISSUE_KEY"

      - name: Fetch Jira Description
        id: jira
        run: |
          if [ -n "${{ steps.jira_key.outputs.issue_key }}" ]; then
            RESPONSE=$(curl -s -X GET \
              -H "Authorization: Bearer ${{ secrets.JIRA_TOKEN }}" \
              -H "Accept: application/json" \
              "https://tusharnigam88.atlassian.net/rest/api/3/issue/${{ steps.jira_key.outputs.issue_key }}")
          
            DESCRIPTION=$(echo "$RESPONSE" | jq -r '.fields.description.content[].content[].text' | tr '\n' ' ')
            echo "description=$DESCRIPTION" >> $GITHUB_OUTPUT
            echo "Fetched Jira Description: $DESCRIPTION"
          else
            echo "description=" >> $GITHUB_OUTPUT
            echo "No Jira issue key found."
          fi

      - name: Check PR Size
        id: pr_size
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            core.setOutput("changed_files", pullRequest.changed_files);

      - name: Generate Class-Wise AI Review
        id: ai
        if: steps.pr_size.outputs.changed_files <= 100
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Generating class-wise AI review..."

          DIFF_CONTENT=$(cat pr_diff.txt)
          PR_DIFF=$(echo "$DIFF_CONTENT" | base64 -w 0)
          JIRA_DESC="${{ steps.jira.outputs.description }}"

          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"contents\": [{
                \"parts\": [{
                  \"text\": \"You are a senior Flutter reviewer. Decode the base64 diff and use the Jira description to generate a PR review.\\n
                  ### Jira Description:\\n$JIRA_DESC\\n
                  ### Instructions:\\n
                  - Split feedback by each class and file separately.\\n
                  - For each class, describe:\\n
                    * Purpose\\n
                    * Changes made\\n
                    * Potential issues or risks\\n
                    * Testing notes\\n
                  ### Base64 diff:\\n$PR_DIFF\"
                }]
              }]
            }")

          echo "----- RAW GEMINI RESPONSE -----"
          echo "$RESPONSE"

          SUMMARY=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          echo "----- Extracted Summary -----"
          echo "$SUMMARY"

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Debug AI Output
        run: |
          echo "AI Summary Output:"
          echo "${{ steps.ai.outputs.summary }}"

      - name: Post Class-Wise Review as PR Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
          script: |
            const summary = `${{ steps.ai.outputs.summary }}`;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🧠 AI PR Review (Class-Wise with Jira Context)\n\n${summary}`
            });
