name: AI PR Review Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PR_COMMENT_TOKEN secret is set
        run: |
          if [ -z "${{ secrets.PR_COMMENT_TOKEN }}" ]; then
            echo "❌ PR_COMMENT_TOKEN secret is NOT set."
            exit 1
          else
            echo "✅ PR_COMMENT_TOKEN secret is available."
          fi

      - name: Get PR Diff
        env:
          GITHUB_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
        run: |
          echo "Fetching PR diff for PR #${{ github.event.pull_request.number }}"
          curl -s -H "Accept: application/vnd.github.v3.diff" \
               -H "Authorization: token $GITHUB_TOKEN" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > pr_diff.txt

          echo "----- 📄 First 100 lines of PR Diff -----"
          head -n 100 pr_diff.txt

      - name: Generate AI Summary
        id: ai
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Generating structured AI-based PR summary..."

          DIFF_CONTENT=$(cat pr_diff.txt)
          if [ ${#DIFF_CONTENT} -gt 15000 ]; then
            echo "⚠️ Diff too large, truncating..."
            DIFF_CONTENT=$(echo "$DIFF_CONTENT" | head -c 15000)
          fi

          PR_DIFF=$(echo "$DIFF_CONTENT" | base64 -w 0)

          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"contents\": [{
                \"parts\": [{
                  \"text\": \"You are a senior Flutter reviewer. Decode the base64 diff and provide:\n
                  - Overall purpose of this PR\n
                  - Changed files and their role\n
                  - Potential impact on the app\n
                  - Risks or testing notes\n
                  Output in markdown format with sections: Purpose, Changes, Impact, Notes.\n
                  Base64 diff:\n\n$PR_DIFF\"
                }]
              }]
            }")

          echo "----- 🤖 RAW GEMINI RESPONSE -----"
          echo "$RESPONSE"

          SUMMARY=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          echo "----- ✍️ Extracted Summary -----"
          echo "$SUMMARY"

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post Summary as PR Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_COMMENT_TOKEN }}
          script: |
            const summary = process.env.SUMMARY;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🤖 AI PR Review Summary\n\n${summary}`
            });
        env:
          SUMMARY: ${{ steps.ai.outputs.summary }}
