name: PR Summary with MCP

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install axios

      - name: Fetch PR Data via MCP
        env:
          GITHUB_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
        run: |
          node scripts/fetch-pr-data.js

      - name: Generate Summary with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          node scripts/summarize-pr-gemini.js

      - name: Comment on PR
        run: gh pr comment ${{ github.event.pull_request.number }} --body-file summary.md
        env:
          GITHUB_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
