name: Test GitHub MCP Context Fetch

on:
  workflow_dispatch:  # Allows manual run from Actions tab

jobs:
  fetch-mcp-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Context from GitHub MCP
        id: github_mcp
        run: |
          echo "Fetching PR context via MCP server..."
          CONTEXT=$(gh api \
            /repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/context \
            --jq '.context' || echo "No MCP context available")
          echo "Context fetched: $CONTEXT"
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT
